### ISSUE TITLE
Teleporting to mars (and probably any planet) crashes the game

### ISSUE THREAD

**Issue by ShirodoBurak** [st0x0ef/stellaris#15]
Neoforge version : 1.21.1-21.1.1
Mod list:

- [OctoLib (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/octo-lib)
- [Eyes in the Darkness (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/eyes-in-the-darkness)
- [NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
- [FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
- [Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
- [Excavated Variants (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/excavated-variants)
- [Dynamic Asset Generator (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/dynamic-asset-generator)
- [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
- [DnT End Castle Standalone (by Nova_Wostra)](https://www.curseforge.com/minecraft/mc-mods/dnt-end-castle-standalone)
- [Cold Sweat (by Mikul)](https://www.curseforge.com/minecraft/mc-mods/cold-sweat)
- [Forgiving Void (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/forgiving-void)
- [Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
- [Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
- [CoroUtil (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/coroutil)
- [Utility Belt (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/utility-belt)
- [Fish On The Line (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/fish-on-the-line)
- [Extra Delight (by Lance5057)](https://www.curseforge.com/minecraft/mc-mods/extradelight)
- [Tree Harvester (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
- [Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
- [CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
- [Better Beacon Placement (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/better-beacon-placement)
- [Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
- [Expanded Delight (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
- [Formations (Structure Library) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/formations)
- [Chunk Loaders (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
- [[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
- [Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
- [Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
- [Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
- [Fast IP Ping (by Fallen_Breath)](https://www.curseforge.com/minecraft/mc-mods/fast-ip-ping)
- [You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
- [SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
- [Chalk (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/chalk)
- [Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
- [JourneyMap Integration (by frankV)](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration)
- [FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
- [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
- [Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
- [Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
- [DnT Stronghold Overhaul (by Nova_Wostra)](https://www.curseforge.com/minecraft/mc-mods/dnt-stronghold-overhaul)
- [Sit (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/sit)
- [Cardiac (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/cardiac)
- [Project: Vibrant Journeys (by OrderedChaosDev)](https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys)
- [Wither Skeleton Tweaks (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/wither-skeleton-tweaks)
- [Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
- [Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
- [Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
- [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
- [Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
- [ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
- [Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
- [Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
- [Expanded Storage (by Quinn451)](https://www.curseforge.com/minecraft/mc-mods/expanded-storage)
- [What Are They Up To (Watut) (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/what-are-they-up-to)
- [Hearths (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/hearths)
- [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
- [BadOptimizations (by thosea)](https://www.curseforge.com/minecraft/mc-mods/badoptimizations)
- [AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
- [MapFrontiers (by meme_sapiens)](https://www.curseforge.com/minecraft/mc-mods/mapfrontiers)
- [SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
- [Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
- [JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
- [Formations Nether (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/formations-nether)
- [Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
- [Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
- [Curios API Continuation (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/curios-continuation)
- [ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
- [Not Enough Recipe Book [NERB] (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)
- [PneumaticCraft: Repressurized (by desht_08)](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)
- [Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
- [Dense Trees (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/dense-trees)
- [JamLib (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/jamlib)
- [DnT Nether Fortress Overhaul (by Nova_Wostra)](https://www.curseforge.com/minecraft/mc-mods/dnt-nether-fortress-overhaul)
- [Jumbo Furnace (by Commoble)](https://www.curseforge.com/minecraft/mc-mods/jumbo-furnace)
- [Wooden Shears (by thecech12)](https://www.curseforge.com/minecraft/mc-mods/wooden-shears)
- [Enchanted Vertical Slabs (by Enchanted_Games)](https://www.curseforge.com/minecraft/mc-mods/enchanted-vertical-slabs)
- [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
- [Accessories (by Blodhgarm)](https://www.curseforge.com/minecraft/mc-mods/accessories)
- [OfflineSkins (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/offlineskins)
- [Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
- [Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
- [Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
- [Healing Campfire (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
- [Ceiling Torch (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/ceiling-torch)
- [Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
- [[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
- [Sophisticated Storage (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
- [spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
- [Trash Cans (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/trash-cans)

### **How to produce :** 
	Directly TP to any dimension stellaris adds. It successfully teleports but after a couple hundreds of milliseconds, game just crashes with the latest.log and crash log attached below
	
	
	
[latest.log](https://github.com/user-attachments/files/16648479/latest.log)
[crash-2024-08-18_15.41.41-client.txt](https://github.com/user-attachments/files/16648460/crash-2024-08-18_15.41.41-client.txt)

**Comment by st0x0ef** [comment]
fixed in 1.0.5
