### ISSUE TITLE
missing fluid texture causes a crash with EMI

### ISSUE THREAD

**Issue by Saereth** [st0x0ef/stellaris#17]
Originally reported here but brought over as it seems to be a Stellaris issue

https://github.com/emilyploszaj/emi/issues/674

mc: 1.21.1
Neoforge: 21.1.22
JEI: jei-1.21.1-neoforge-19.8.4.113
EMI: emi-1.1.11+1.21+neoforge
Stellaris: stellaris-1.21-neoforge-1.0.5
Xycraft: xycraft_core-0.7.45-all
xycraft_machines-0.7.45
xycraft_world-0.7.45

So what happens is when you search for oil in EMI the game crashes trying to render tanks with stellaris oil. If I remove stellaris it's fine.

https://mclo.gs/NlmXqzM

**Comment by TathanDev** [comment]
Fixed since a long time x)
