### ISSUE TITLE
Error "Duplicate key key_key.stellaris.rocket_start" while starting. stellaris-1.21-neoforge-1.0.1

### ISSUE THREAD

**Issue by JayBeee99** [st0x0ef/stellaris#18]
Happens sometimes
The mod writes duplicate entries in optios.txt file in .minecraft folder.

Following entriy appears:
```
key_key.stellaris.rocket_start:key.keyboard.space
key_key.stellaris.freeze_planet_menu:key.keyboard.x
key_key.stellaris.jetsuit_mode:key.keyboard.v
key_key.stellaris.rocket_start:key.keyboard.space
key_key.stellaris.freeze_planet_menu:key.keyboard.x
key_key.stellaris.jetsuit_mode:key.keyboard.v
```
After deleting duplicate lines the game starts.
Bug apears on 3 different computers.

[crashdump error duplicate key stellaris.txt](https://github.com/user-attachments/files/16752673/crashdump.error.duplicate.key.stellaris.txt)

**Comment by st0x0ef** [comment]
this is already fixed, try with the latest version

**Comment by JayBeee99** [comment]
These duplicate lines reapear very often. We need to delete the lines mostly every time we start our game.
