### ISSUE TITLE
Meteor 6 structure chest spawns with incorrect loot table

### ISSUE THREAD

**Issue by STS15** [st0x0ef/stellaris#19]
Neoforge 21.1.31
Stellaris 1.0.7

The meteor chest spawns with the loot table "minecraft:chests/meteor" which doesn't exist so it needs to be changed to the correct namespace "stellaris:chests/meteor".  Tested spawning some chests in with this name space and it seems to work properly.

**Comment by STS15** [comment]
I was able to output the loot table for all the meteors to confirm the error is only on meteor_6.nbt

Meteor 1:
/setblock 11675 144 -10406 minecraft:chest[facing=west,type=single,waterlogged=false]{LootTable:"stellaris:chests/meteor",LootTableSeed:3458811427982471077L}

Meteor 2:
/setblock 11675 142 -10406 minecraft:chest[facing=west,type=single,waterlogged=false]{LootTable:"stellaris:chests/meteor",LootTableSeed:285647358581288634L}

Meteor 3:
/setblock 11629 143 -10406 minecraft:chest[facing=east,type=single,waterlogged=false]{LootTable:"stellaris:chests/meteor",LootTableSeed:7865854469976540157L}

Meteor 4:
/setblock 11629 145 -10452 minecraft:chest[facing=south,type=single,waterlogged=false]{LootTable:"stellaris:chests/meteor",LootTableSeed:-2365265974043034505L}

Meteor 5:
/setblock 11675 142 -10452 minecraft:chest[facing=east,type=single,waterlogged=false]{LootTable:"stellaris:chests/meteor",LootTableSeed:1253805497860823620L}

Meteor 6:
/setblock 11674 176 -10406 minecraft:chest[facing=north,type=single,waterlogged=false]{LootTable:"minecraft:chests/meteor",LootTableSeed:2267904103850473420L}

**Comment by TathanDev** [comment]
Will be fixed in the new update !
