### ISSUE TITLE
[NeoForge 1.21.1] OpenGL Errors

### ISSUE THREAD

**Issue by Darkfiend009** [st0x0ef/stellaris#22]
I am making a modpack and wanted to include Stellaris! However, i am getting this error a lot in my logs regarding OpenGL texture errors and wanted to report. Let me know if i can send any additional information to help

![image](https://github.com/user-attachments/assets/689d952c-f17a-4bd4-8e1a-67426cdfa428)

**Comment by st0x0ef** [comment]
Thanks for the report, we'll check that. Can you just say us when does that happen?

**Comment by Darkfiend009** [comment]
After i load into a world, they appear in the log.  No interactions or doing anything other than walking around.

**Comment by st0x0ef** [comment]
Does everything seem to work good (in the sky)?

**Comment by Darkfiend009** [comment]
I can see the custom skybox with all the different stars at night, yes.

**Comment by st0x0ef** [comment]
Seem to be on your side only, try updating your GPU driver
https://www.partitionwizard.com/partitionmanager/opengl-error-1282.html

**Comment by Darkfiend009** [comment]
Drivers have been updated. The error still persists in the log, unfortunately.

Just to clarify, the error doesn't crash the client or anything severe like that. I just saw it while i was working on the modpack and thought it might be helpful to report it.

**Comment by TathanDev** [comment]
fixed

**Comment by st0x0ef** [comment]
> fixed

How?

**Comment by st0x0ef** [comment]
That's not a fix...

**Comment by TathanDev** [comment]
With a little bit of magic and beautiful return 😉
