### ISSUE TITLE
NeoForge 1.21.1 - Huge FPS drops when equipping any one piece of the Jet Suit 

### ISSUE THREAD

**Issue by ZyrusHub** [st0x0ef/stellaris#23]
I am currently playing on neo forge version of your mod through the curse forge launcher, I am not able to post an issue or comment on their so i had to post here .

I was on creative mode testing out your mod to see if there was any issues before i went into survival so im not sure if this occurs when in survival mode. I am also using a mod pack called All The Mods 10 which could be an issue but i have also seen on curseforge that there is one person who has also had a problem when hoving over the jet suit and his game crashes expect for me its when i put on the jet suit in my inventory i get around a
75% frame rate drop.

**Comment by TathanDev** [comment]
Thanks for report !

**Comment by ZyrusHub** [comment]
No problem would love to see this mod grow!

**Comment by st0x0ef** [comment]
Does this bug still append in Stellaris 1.1?
