### ISSUE TITLE
[NeoForge] Issue connecting to server with 1.1.0

### ISSUE THREAD

**Issue by Darkfiend009** [st0x0ef/stellaris#24]
I updated Stellaris to version 1.1.0 on my server. However, i now cannot connect to the server since the update. I pulled a log that might be able to help.

Log: https://gist.github.com/Darkfiend009/cd9ea13ccb27d39fc5e88726d64b3292

Minecraft 1.21.1
NeoForge: 21.1.42
Stellaris: 1.1.0

**Comment by TathanDev** [comment]
New update soon with the fix !
