### ISSUE TITLE
I made a Chinese Simplified Chinese translation

### ISSUE THREAD

**Issue by shenyx110** [st0x0ef/stellaris#25]
I made a Chinese Simplified Chinese translation
我制作了简体中文翻译
[zh_cn.json](https://github.com/user-attachments/files/17100731/zh_cn.json)

如果有遗漏或者后续更新我会尽量跟进
If there are any omissions or subsequent updates, I will try to follow up

**Comment by st0x0ef** [comment]
simplified chinesse is already in the mod

thanks anyway ;)
