### ISSUE TITLE
It seems that this mod will cause the EMI to crash

### ISSUE THREAD

**Issue by shenyx110** [st0x0ef/stellaris#26]
It seems that this mod will cause the EMI to crash
[minecraft-exported-crash-info-2024-09-24T00-33-15.zip](https://github.com/user-attachments/files/17100946/minecraft-exported-crash-info-2024-09-24T00-33-15.zip)
[minecraft-exported-logs-2024-09-24T00-32-48.log](https://github.com/user-attachments/files/17100948/minecraft-exported-logs-2024-09-24T00-32-48.log)
[minecraft-exported-logs-2024-09-24T00-33-23.log](https://github.com/user-attachments/files/17100949/minecraft-exported-logs-2024-09-24T00-33-23.log)

**Comment by TathanDev** [comment]
Thanks for the report.
I don't think the problem can be fixed by us but we will take a look!
Maybe you can also report this to EMI.

**Comment by TathanDev** [comment]
I tested with Stellaris `1.1.1`, Architectury `13.0.6+neoforge` and EMI `1.1.13+1.21.1+neoforge` and everything works
