### ISSUE TITLE
Rocket crafting with FTB Direwolf20 1.21 1.1.2

### ISSUE THREAD

**Issue by Blitzmars** [st0x0ef/stellaris#27]
Hello,

with the Feed the Beast Modpack Direwolf20 1.21 / 1.1.2 it is not possible to craft the Rocket in the rocket crafting station.

As far as I know it is because it only accepts Steel Ingots from your stellaris mod.
But in this modpack you will get only steel ingots from mekanism mod.

**Comment by TathanDev** [comment]
The item needed is now set to the `c:ingots/steel` tag so it's should be compatible with mekanism Steel too.

But we will investigate about this issue !

Thanks for the report!

**Comment by TathanDev** [comment]
I tested with stellaris steel and mekanism steel and it's works for both.
I use Mekanism `10.7.7.64` and Stellaris `1.1.1` (The 1.1.2 version doesn't exist)

https://github.com/user-attachments/assets/7a7be141-26c0-4428-9062-af5a6bd9a0ad

**Comment by Blitzmars** [comment]
Hi,
sorry for the misunderstanding.
FTB Direwolf20 has the it's own version 1.1.2 and the Minecraft version 1.21.
It seems to use the stellaris 1.0.10.
Is the video before or after the  `c:ingots/steel tag` change?

**Comment by TathanDev** [comment]
Yea I thought it was Stellaris 1.1.2 (sorry about that)
This video is after the tag change.
But we already asked to FTB to update the mod and a new pack update should be up soon !

**Comment by Blitzmars** [comment]
Thank you very much.

**Comment by Blitzmars** [comment]
Quick notice:
FTB updated the pack today.
It works.
