### ISSUE TITLE
Very Minor issue, but it seems you can't jump when the Rocket Start default keybind is set to Spacebar. 

### ISSUE THREAD

**Issue by Greg727** [st0x0ef/stellaris#28]
While it was set to spacebar I couldn't jump at all, assigning it a different key fixes the issue, but I get the feeling it's not supposed to do that.

**Comment by TathanDev** [comment]
Yea, that is definetly weird
Which modloader/minecraft version/stellaris version are you using ?

**Comment by Greg727** [comment]
Fabric

**Comment by Greg727** [comment]
1.21.1

**Comment by Greg727** [comment]
Latest Version for 1.21.1

**Comment by TathanDev** [comment]
Thanks for the report ! We will take a loot !

**Comment by st0x0ef** [comment]
fixed !
