### ISSUE TITLE
Minor Issue, Mod Crashes if you attempt to shift click a bucket into the pumpjack

### ISSUE THREAD

**Issue by KaiserCheese** [st0x0ef/stellaris#29]
Latest version 1.1.1 in the DW20 1.21.1 pack. Game crashes if you attempt to shift click a bucket into the pumpjack. 
Crashlog for reference: https://pastebin.com/scQvvSbh

**Comment by TathanDev** [comment]
We tested this in our dev environment and nothing crash. But we saw that the inventory size value was too high for the pumpjack menu and we fixed it with 375ad7e so the crash could be here because of this.
