### ISSUE TITLE
Oil Disappears from a Chunk if you close and reopen the world. 

### ISSUE THREAD

**Issue by KaiserCheese** [st0x0ef/stellaris#30]
I do not know if this intended but every time I launch the pack, the chunks which have oil change. If it is intended, it might make more sense to give the full pumpjack when mining it, since it punishes the player for not fully extracting it in one session which is sort of unreasonable.

This is also the latest version of the mod, 1.1.1 in 1.21.1 DW20 pack.

**Comment by st0x0ef** [comment]
Thanks for the report, we're working on that
