### ISSUE TITLE
Suggestion: Increase the damage from lack of oxygen but decrease oxygen use.

### ISSUE THREAD

**Issue by KaiserCheese** [st0x0ef/stellaris#31]
It seems kind of pointless to get oxygen because the only real penalty is you take marginal damage. I flew to the moon looking for desh and ran out of oxygen in like 5 minutes despite having 5000+ in my suit. But after I ran out, I realized I didnt actually need oxygen because the damage you take is so minimal and you can just facetank it with food. 

My suggestion would be to massively increase the damage you take from not having oxygen but decrease the rate at which it drains.

**Comment by eirmax** [comment]
Thanks for reporting
