### ISSUE TITLE
Loading into worlds hangs with stellaris 1.1.2

### ISSUE THREAD

**Issue by antisocialian** [st0x0ef/stellaris#32]
i don't see anything specific to stellaris in the logs, but on version 1.1.1 i can load into a map fine and on 1.1.2 it hangs on loading the world(the little square fills and the counter says 100% but it never loads and the logs show that it didn't actually load 100%).

Due to my logs being too big for pastebin (i'm limited to 512k per paste i guess now, haven't used it much recently) i've put the latest.log and debug.log in my dropbox:

- https://www.dropbox.com/scl/fi/mrx6010kzsdnngucoo7wt/debug.log?rlkey=sy9kadzomsupddm07gzou59xw&dl=0
- https://www.dropbox.com/scl/fi/txe3g11h1nk244dwyn7fb/latest.log?rlkey=7app3hp4uaxz648w49q3wswct&dl=0

i have tried on different versions of neoforge from 21.1.61 thru 21.1.64 i have the newest versions of the architectury api(13.0.6) and the sky aesthetics(1.2.2). I have tried removing references to stellaris in the kubejs scripts as i had read something about the steel changing and figured that could be a problem.

unfortunately loading a much smaller modpack doesn't have the same issue, so i'm assuming there must be an issue with 1.1.2 being incompatible with another mod?

the pack i'm using was the direwolf20 1.21.1 pack(version 1.2.1) but i added a few other mods, tweaked things and such.

**Comment by antisocialian** [comment]
This is an export of the pack i've got so far. i haven't changed the graphics for the menu yet, those are still the direwolf20 ones
https://www.dropbox.com/scl/fi/0v2mzb0sgcfq15pe8xmav/REMIX-1.0.0.zip?rlkey=uc92k6sfvearb56wuckvsnykj&dl=0

**Comment by st0x0ef** [comment]
I'm not able to reproduce that issue, do you've enough ram allocated to your game?

**Comment by antisocialian** [comment]
8gb, probly could go up to 10 or 12 before i run into problems from windows.

would be a lot easier to diagnose if the log told us what it was actually doing. i've disabled the discord plugin since i'm only playing solo and i don't care for everyone to know i'm in the overworld of whatever. also disabled littletiles since i'm not creative enough for that and it was causing issues when villagers went to bed for some reason.

Just tried Raising it to 12gb, creating a new world, and it is still stuck on the 100% with the square, but not saying loading terrain. Windows Task manager slowly went up from just under 7gb when it hit 100% to just under 13gb after about 13minutes(ish). The log shows a bunch of messages from modernfix and spark, i'm fairly certain spark is innocuous but modernfix might change some world gen maybe?

trying again set to 12gb, with modernfix and spark disabled again. still about the same increase in ram overtime. I do notice Productive bees mentioning spawning hives near the bottom of the log. the last thing in the log is stuff from AE2 as well. nothing happens in the log after 15min after the AE2 stuff.

also disabled ae2(and the 13 things that depend on it), and it loads fine. https://www.dropbox.com/scl/fi/m3ds2cqkah9kauhqd8q2t/no-modernfix-spark-ae2-debug.log?rlkey=zgs1hzgwoayi6ouiwekkq1iat&dl=0

going back thru, modernfix and spark work fine. ae2, extendedae, ae2things, advancedae, Applied Energistics 2 Wireless Terminals, Applied Mekanistics, [Forge] AE2 Additional Opportunity, AE2 JEI Integration, and ME Requester all work fine.

with megacells enabled it fails again.

trying a new empty pack with just stellaris, architectury api, ae2, and mega cells on neoforge 21.1.64 and that also loads fine.

i have no idea now what the problem is. but with my mods i guess i probly don't use the mega cells that much, just that i know that isn't the root cause and i'm sure stellaris isn't either.

**Comment by st0x0ef** [comment]
Maybe you should ask to the ftb team to fix the compatibility issue in their pack, I can't do anything...
