### ISSUE TITLE
1.21 Bug with ores

### ISSUE THREAD

**Issue by Based199** [st0x0ef/stellaris#33]
Breaking other planets ores with fortune will return the block itself rather than the raw ore/gem/dust etc

e.g. breaking venus gold ore with fortune pickaxe will give venus gold ore.

**Comment by st0x0ef** [comment]
which ore?

**Comment by Based199** [comment]
seems to be all of them. 
 
to be specific, that list includes: Steel Ore, Deepslate Steel ore, Mercury Uranium Ore, Moon Steel Ore, Mars Iron Ore, Mars Ostrum Ore, Mars Plutonium Ore, Mars Ice Shard Ore, Mars Diamond Ore, Venus Coal Ore, Venus Neptunium Ore, Venus Gold Ore, Venus Diamond Ore, Moon Desh Ore, Moon Ice Shard Ore, Moon Iron Ore, and Mercury Iron Ore.


also small side note, when i tried breaking Moon Steel Ore i was actually unable to using any vanilla pickaxe, however using other mods tools worked fine

**Comment by flyover0112** [comment]
Tried to break with netherite paxel also resulted in getting the whole block as I would silk touch it.

**Comment by st0x0ef** [comment]
fixed !
