### ISSUE TITLE
Conflicting Ores

### ISSUE THREAD

**Issue by Rappstar285** [st0x0ef/stellaris#34]
I’m trying to make steel blocks for the fuel refinery, but when I make steel blocks (I have installed Energized Power and Mythic Metals) it reverts to the mythic metals Steel block (I am using the Stellaris ingots) I am soft locked in my server that I’ve played on for a month.

**Comment by st0x0ef** [comment]
Use this mod https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by Rappstar285** [comment]
Thank you! It worked! 
However, I am unable to get oil out of the Pumpjack. I found a vein that is 9000 units. I put a bucket in the top slot of the pumpjack and it doesn’t fill the bucket (I’m assuming the measurements are in mB where 1 bucket is 1000mB?)

**Comment by st0x0ef** [comment]
Do you've give energy to the pump?

**Comment by Rappstar285** [comment]
Yes, it is powered via a heat generator and has extracted all the oil from the vein. Power is currently showing 6000/6000.

**Comment by Rappstar285** [comment]
I am also playing on Fabric 1.21 if that means anything. I don’t know if different mods have different unit sizes for buckets

**Comment by st0x0ef** [comment]
Are you using the latest version (1.1.3) ?

If no, try updating and finding a new chunk (newly created) to get the good value 

For an unknown reason, fabric bucket's hold 81000mb instead of 1000 😞

**Comment by Rappstar285** [comment]
I just saw that the most current update is 1.1.3, not 1.1.2

that should fix it! Thank you!
