### ISSUE TITLE
[BUG] Stuck on Solar System screen and locks up Minecraft

### ISSUE THREAD

**Issue by Tsoccerguy3** [st0x0ef/stellaris#35]
Using neoforge-21.1.65 and stellaris-1.21-neoforge-1.1.3 .
After I launch into space I am stuck on the Solar system screen and it is locked there , No way to exit this screen using any keys , The ESC does nothing . I had to close Minecraft .

**Comment by Tsoccerguy3** [comment]
Also , I was not able to find any instructions, Recipes or any information on the mods use.

**Comment by st0x0ef** [comment]
> Also , I was not able to find any instructions, Recipes or any information on the mods use.

Our wiki : https://st0x0ef.github.io/stellaris/wiki/getting-started.html
You can also use JEI or REI to see all recipes

**Comment by st0x0ef** [comment]
> Using neoforge-21.1.65 and stellaris-1.21-neoforge-1.1.3 . After I launch into space I am stuck on the Solar system screen and it is locked there , No way to exit this screen using any keys , The ESC does nothing . I had to close Minecraft .

To close the menu, you need to select a planet/moon and teleport you to it. If you want to come back, you just need to select the earth.
