### ISSUE TITLE
Conversion recipes use wrong recipe type

### ISSUE THREAD

**Issue by rlnt** [st0x0ef/stellaris#39]
Your conversion recipes from blocks to ingots currently use a shaped recipe.
https://github.com/st0x0ef/stellaris/blob/1.21/common/src/main/resources/data/stellaris/recipe/misc/steel_ingot.json

This breaks vanilla convention as they are using shapeless recipes for this. An example would be the iron block to iron ingots.
iron_ingot_from_iron_block.json
```json
{
  "type": "minecraft:crafting_shapeless",
  "category": "misc",
  "group": "iron_ingot",
  "ingredients": [
    {
      "item": "minecraft:iron_block"
    }
  ],
  "result": {
    "count": 9,
    "id": "minecraft:iron_ingot"
  }
}
```

This applies to recipes for ingots to nuggets as well.
https://github.com/st0x0ef/stellaris/blob/1.21/common/src/main/resources/data/stellaris/recipe/misc/steel_nugget.json

**Comment by TathanDev** [comment]
Thanks for the report ! It should be good now !
