### ISSUE TITLE
Nothing happens when we press space

### ISSUE THREAD

**Issue by jziolkowski** [st0x0ef/stellaris#40]
My kid plays in creative. Feather launcher, installed today. Deps pulled automatically.

Built the pad, placed the rocket (but I see in the source the fuel is not needed on creative). Pressing space doesn't do anything.

Pls advise.

**Comment by Tsoccerguy3** [comment]
Left shift click on rocket and add the appropriate parts to the rocket template. Then click on rocket to enter and spacebar to launch

**Comment by TathanDev** [comment]
You need to change your keybinds.

**Comment by jziolkowski** [comment]
Which keybind exactly? Space is bound to jump as default
