### ISSUE TITLE
[Crash/Bug] Crashing when going to the Moon

### ISSUE THREAD

**Issue by alfredggttv** [st0x0ef/stellaris#45]
Testing out the functionality of the mod on a server.

1. Placed rocket launch pad, rocket on top. Gave rocket 2 buckets of fuel
2. Launched into Space
3. Screen opens, I select the moon.
4. Game immediately crashes.

Once I reconnect, I'm in the space screen again and choosing the moon or earth results in another crash with the same error.

Log: https://mclo.gs/87N6mZq
MC Version: 1.21.1
Neoforge v. 21.1.71
Mod version: stellaris-1.21-neoforge-1.1.7

**Comment by st0x0ef** [comment]
From which dimension are you starting?

**Comment by alfredggttv** [comment]
I launched from a different dimension, the void dimension from Just Another Void Dim mod.

**Comment by st0x0ef** [comment]
fixed in the next update!
