### ISSUE TITLE
Hotbar issue when entering a new planet

### ISSUE THREAD

**Issue by Pyro124** [st0x0ef/stellaris#9]
Whenever I enter a new planet makes my scroll wheel not go through the different items in my hotbar.

**Comment by st0x0ef** [comment]
Can you send some screenshot or a video please?

**Comment by Pyro124** [comment]
https://www.mediafire.com/file/x4o0vokjmxgncs8/Untitled+video+-+Made+with+Clipchamp.mp4/file

**Comment by Pyro124** [comment]
https://www.mediafire.com/file/x4o0vokjmxgncs8/Untitled+video+-+Made+with+Clipchamp.mp4/file

**Comment by st0x0ef** [comment]
Ok I'll check what cause that issue

**Comment by TathanDev** [comment]
Fixed in the next update
